/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication30;

import Animacion.Animacion;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.LayoutManager;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author tonyj
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        pcen.setVisible(false);
        /*Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        int ancho = (int)d.getWidth();
        int alto = (int)d.getHeight();*/
        
        panelIZ.setVisible(false);
        Animacion.mover_izquierda(0, -270, 1, 9, panelIZ);
        plog.setBackground(new java.awt.Color(0, 0, 0,160));
        txtuser.setOpaque(false);
        txtuser.setBounds(50, 30, 90, 40);
        txtpass.setOpaque(false);
        txtpass.setBounds(50, 30, 90, 40);
        lblicon.setVisible(false);

        //puser.setOpaque(false);
        ImageIcon ic2 = new ImageIcon(getClass().getResource("/img/Muebles-modulares-vs-muebles-a-medida.jpg"));
        Icon ics2 = new ImageIcon(ic2.getImage().getScaledInstance(lblimg.getWidth(),lblimg.getHeight(), Image.SCALE_DEFAULT));
        lblimg.setIcon(ics2);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        panelIZ = new javax.swing.JPanel();
        pven = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pven1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pcen = new javax.swing.JPanel();
        pcosas = new javax.swing.JPanel();
        pcont3 = new javax.swing.JPanel();
        pcontr = new javax.swing.JPanel();
        jTextPane4 = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtprodv7 = new javax.swing.JTextField();
        txtprodv8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        pvent1 = new javax.swing.JPanel();
        jTextPane5 = new javax.swing.JTextPane();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtprodv9 = new javax.swing.JTextField();
        txtprodv10 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        plog = new javax.swing.JPanel();
        lblnom = new javax.swing.JLabel();
        lblnom1 = new javax.swing.JLabel();
        txtpass = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panelAR = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblicon = new javax.swing.JLabel();
        lblpag = new javax.swing.JLabel();
        lblimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelIZ.setBackground(new java.awt.Color(51, 51, 51));

        pven.setBackground(new java.awt.Color(51, 51, 51));
        pven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pvenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pvenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pvenMouseExited(evt);
            }
        });
        pven.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-money-48.png"))); // NOI18N
        pven.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ventas Del Dia");
        pven.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 130, 60));

        pven1.setBackground(new java.awt.Color(51, 51, 51));
        pven1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pven1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pven1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pven1MouseExited(evt);
            }
        });
        pven1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-new-product-48.png"))); // NOI18N
        pven1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 60));

        jLabel18.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Inventario");
        pven1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 100, 60));

        javax.swing.GroupLayout panelIZLayout = new javax.swing.GroupLayout(panelIZ);
        panelIZ.setLayout(panelIZLayout);
        panelIZLayout.setHorizontalGroup(
            panelIZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIZLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pven, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(pven1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelIZLayout.setVerticalGroup(
            panelIZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIZLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pven, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pven1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(591, Short.MAX_VALUE))
        );

        jPanel3.add(panelIZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 260, 730));

        pcen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pcosas.setBackground(new java.awt.Color(238, 238, 221));
        pcosas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pcont3.setBackground(new java.awt.Color(238, 238, 221));
        pcont3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pcont3.setForeground(new java.awt.Color(102, 102, 102));
        pcont3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pcontr.setBackground(new java.awt.Color(238, 238, 221));

        jTextPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextPane4.setAutoscrolls(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Codigo:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Cantidad :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Descripcion :");

        txtprodv7.setBackground(new java.awt.Color(238, 238, 221));
        txtprodv7.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        txtprodv7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtprodv7.setCaretColor(new java.awt.Color(51, 51, 51));
        txtprodv7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodv1ActionPerformed(evt);
            }
        });
        txtprodv7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprodv1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprodv1KeyTyped(evt);
            }
        });

        txtprodv8.setBackground(new java.awt.Color(238, 238, 221));
        txtprodv8.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        txtprodv8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtprodv8.setCaretColor(new java.awt.Color(51, 51, 51));
        txtprodv8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodv2ActionPerformed(evt);
            }
        });
        txtprodv8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprodv2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprodv2KeyTyped(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Listo");

        javax.swing.GroupLayout pcontrLayout = new javax.swing.GroupLayout(pcontr);
        pcontr.setLayout(pcontrLayout);
        pcontrLayout.setHorizontalGroup(
            pcontrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pcontrLayout.createSequentialGroup()
                .addGroup(pcontrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pcontrLayout.createSequentialGroup()
                        .addGroup(pcontrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(pcontrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtprodv7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprodv8, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pcontrLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 107, Short.MAX_VALUE))
            .addGroup(pcontrLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pcontrLayout.setVerticalGroup(
            pcontrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pcontrLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pcontrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprodv8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pcontrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pcontrLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pcontrLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txtprodv7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pcontrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pcontrLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pcontrLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jTextPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pcont3.add(pcontr, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 470, 510));

        pvent1.setBackground(new java.awt.Color(238, 238, 221));

        jTextPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextPane5.setAutoscrolls(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Codigo:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Cantidad :");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Descripcion :");

        txtprodv9.setBackground(new java.awt.Color(238, 238, 221));
        txtprodv9.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        txtprodv9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtprodv9.setCaretColor(new java.awt.Color(51, 51, 51));
        txtprodv9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodv9txtprodv1ActionPerformed(evt);
            }
        });
        txtprodv9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprodv9txtprodv1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprodv9txtprodv1KeyTyped(evt);
            }
        });

        txtprodv10.setBackground(new java.awt.Color(238, 238, 221));
        txtprodv10.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        txtprodv10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtprodv10.setCaretColor(new java.awt.Color(51, 51, 51));
        txtprodv10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodv10txtprodv2ActionPerformed(evt);
            }
        });
        txtprodv10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprodv10txtprodv2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprodv10txtprodv2KeyTyped(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 51, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Listo");

        javax.swing.GroupLayout pvent1Layout = new javax.swing.GroupLayout(pvent1);
        pvent1.setLayout(pvent1Layout);
        pvent1Layout.setHorizontalGroup(
            pvent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pvent1Layout.createSequentialGroup()
                .addGroup(pvent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pvent1Layout.createSequentialGroup()
                        .addGroup(pvent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(pvent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtprodv9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprodv10, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pvent1Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 107, Short.MAX_VALUE))
            .addGroup(pvent1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pvent1Layout.setVerticalGroup(
            pvent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pvent1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pvent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprodv10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pvent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pvent1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pvent1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txtprodv9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pvent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pvent1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pvent1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jTextPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pcont3.add(pvent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        pcosas.add(pcont3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 620, 560));

        pcen.add(pcosas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 1160, 730));

        jPanel3.add(pcen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 1090, 730));

        plog.setBackground(new java.awt.Color(0, 0, 0));
        plog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblnom.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        lblnom.setForeground(new java.awt.Color(255, 255, 255));
        lblnom.setText("Contraseña");
        plog.add(lblnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 239, 150, 30));

        lblnom1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        lblnom1.setForeground(new java.awt.Color(255, 255, 255));
        lblnom1.setText("Usuario");
        plog.add(lblnom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 128, 107, 30));

        txtpass.setBackground(new java.awt.Color(0, 0, 0));
        txtpass.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        txtpass.setForeground(new java.awt.Color(255, 255, 255));
        txtpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtpass.setCaretColor(new java.awt.Color(51, 51, 51));
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpassKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpassKeyTyped(evt);
            }
        });
        plog.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 201, -1));

        txtuser.setBackground(new java.awt.Color(51, 51, 51));
        txtuser.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        txtuser.setForeground(new java.awt.Color(255, 255, 255));
        txtuser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtuser.setCaretColor(new java.awt.Color(51, 51, 51));
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuserKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuserKeyTyped(evt);
            }
        });
        plog.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 201, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plantilla-login_1017-6719.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        plog.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 349, 197, -1));

        jPanel3.add(plog, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 850, 570));

        panelAR.setBackground(new java.awt.Color(0, 0, 0));
        panelAR.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelARMouseDragged(evt);
            }
        });
        panelAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelARMousePressed(evt);
            }
        });
        panelAR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        panelAR.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, -1, 20));

        lblicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-menu-30.png"))); // NOI18N
        lblicon.setText("jLabel2");
        lblicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbliconMouseClicked(evt);
            }
        });
        lblicon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbliconKeyPressed(evt);
            }
        });
        panelAR.add(lblicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 30, -1));

        lblpag.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblpag.setForeground(new java.awt.Color(255, 255, 255));
        panelAR.add(lblpag, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 300, 40));

        jPanel3.add(panelAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 70));
        jPanel3.add(lblimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 1090, 730));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int xx,xy;
    private void panelARMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelARMousePressed
        xx = evt.getX();
        xy= evt.getY();
    }//GEN-LAST:event_panelARMousePressed

    private void panelARMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelARMouseDragged
        int x=evt.getXOnScreen();
        int y= evt.getYOnScreen();
        
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_panelARMouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void lbliconKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbliconKeyPressed
       
    }//GEN-LAST:event_lbliconKeyPressed
    public void iz(){
        lblicon.setVisible(false);
        if (panelIZ.getX()==0) {
          Animacion.mover_izquierda(500, 300, 1, 2, pcont3);
          Animacion.mover_izquierda(0, -270, 1, 2, panelIZ); 
        }else {
            if (panelIZ.getX()==-270) {
                Animacion.mover_derecha(300,500, 1, 2, pcont3);
                Animacion.mover_derecha(-270,0, 1, 2, panelIZ);
            }
        }
        lblicon.setVisible(true);
    }
    public void ocul(){
        pcontr.setVisible(false);        
        pvent1.setVisible(false);
    }
    
    private void lbliconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbliconMouseClicked
        iz();
    }//GEN-LAST:event_lbliconMouseClicked

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void txtpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyReleased
        
    }//GEN-LAST:event_txtpassKeyReleased

    private void txtpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyTyped

    }//GEN-LAST:event_txtpassKeyTyped

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserKeyReleased

    private void txtuserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserKeyTyped

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plantilla2.jpg"))); 
        
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plantilla-login_1017-6719.jpg"))); 
    }//GEN-LAST:event_jLabel2MouseExited

    private void pvenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvenMouseClicked
        ocul();
        pvent1.setVisible(true);
        lblpag.setText("Ventas");
    }//GEN-LAST:event_pvenMouseClicked

    private void pvenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvenMouseEntered
        pven.setBackground(new java.awt.Color(0,102,0));
    }//GEN-LAST:event_pvenMouseEntered

    private void pvenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvenMouseExited
       pven.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_pvenMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         lblicon.setVisible(true);
         plog.setVisible(false);
         pcen.setVisible(true);
         panelIZ.setVisible(true);
         ocul();
         pvent1.setVisible(true);
         //lblimg.setVisible(false);
         lblpag.setText("Ventas");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtprodv2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprodv2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodv2KeyTyped

    private void txtprodv2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprodv2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodv2KeyReleased

    private void txtprodv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodv2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodv2ActionPerformed

    private void txtprodv1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprodv1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodv1KeyTyped

    private void txtprodv1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprodv1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodv1KeyReleased

    private void txtprodv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodv1ActionPerformed

    private void pven1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pven1MouseEntered
        pven1.setBackground(new java.awt.Color(0,102,0));
    }//GEN-LAST:event_pven1MouseEntered

    private void pven1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pven1MouseExited
        pven1.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_pven1MouseExited

    private void txtprodv9txtprodv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodv9txtprodv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodv9txtprodv1ActionPerformed

    private void txtprodv9txtprodv1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprodv9txtprodv1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodv9txtprodv1KeyReleased

    private void txtprodv9txtprodv1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprodv9txtprodv1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodv9txtprodv1KeyTyped

    private void txtprodv10txtprodv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodv10txtprodv2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodv10txtprodv2ActionPerformed

    private void txtprodv10txtprodv2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprodv10txtprodv2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodv10txtprodv2KeyReleased

    private void txtprodv10txtprodv2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprodv10txtprodv2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodv10txtprodv2KeyTyped

    private void pven1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pven1MouseClicked
       ocul();
       pcontr.setVisible(true);  
       //Animacion.mover_izquierda(940, 80, 1, 2, pcontr); 
       lblpag.setText("Control de Produccion");
    }//GEN-LAST:event_pven1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JLabel lblicon;
    private javax.swing.JLabel lblimg;
    private javax.swing.JLabel lblnom;
    private javax.swing.JLabel lblnom1;
    private javax.swing.JLabel lblpag;
    private javax.swing.JPanel panelAR;
    private javax.swing.JPanel panelIZ;
    private javax.swing.JPanel pcen;
    private javax.swing.JPanel pcont3;
    private javax.swing.JPanel pcontr;
    private javax.swing.JPanel pcosas;
    private javax.swing.JPanel plog;
    private javax.swing.JPanel pven;
    private javax.swing.JPanel pven1;
    private javax.swing.JPanel pvent1;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtprodv10;
    private javax.swing.JTextField txtprodv7;
    private javax.swing.JTextField txtprodv8;
    private javax.swing.JTextField txtprodv9;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
